---
- name: Install utilities
  yum:
    name: unzip
  become: yes

- name: Download and extract terraform
  unarchive:
    src: "{{ terraform_download_url }}"
    dest: "{{ terraform_bin_path }}"
    remote_src: yes
    owner: root
    group: root
    mode: 0755
  become: yes
